# Generated by Django 3.2.18 on 2023-05-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='none', max_length=255)),
                ('user_code', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'email_code_Oasis',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_email', models.EmailField(default='none', max_length=255)),
                ('user_pw', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_registration_date', models.DateField(auto_now=True)),
                ('user_type', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'users_Oasis',
            },
        ),
    ]
