# Generated by Django 3.2.18 on 2023-05-22 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users_Oasis',
        ),
    ]
